FROM maven:3.9.7-eclipse-temurin-21 AS build
WORKDIR build
COPY . .
RUN mvn clean package -pl :at-http-thermometer-device-simulator -am

FROM eclipse-temurin:21-jre
COPY --from=build /build/at-device-simulator/at-http-device-simulator/at-http-thermometer-device-simulator/target/at-http-thermometer-device-simulator-exec.jar application.jar
ENV JAVA_OPTIONS \
    -Dfile.encoding=UTF-8
EXPOSE 8080
SHELL ["/bin/bash", "-c"]
CMD bash -c "java ${JAVA_OPTIONS} -jar application.jar"