services:
  fronted:
    build: frontend
    ports:
      - "4201:80"
    depends_on:
      - backend
    restart: always
  backend:
    build: backend/at-application-bootstrap
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: aura-tower
      MONGODB_USERNAME: root-aura-tower
      MONGODB_PASSWORD: password-aura-tower
  mongodb:
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: aura-tower
      MONGO_INITDB_ROOT_USERNAME: root-aura-tower
      MONGO_INITDB_ROOT_PASSWORD: password-aura-tower
