services:
  web:
    image: bluemek/aura-tower:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo:7.0.8
    ports:
      - "27017:27017"