FROM maven:3.9.7-eclipse-temurin-21 AS build
WORKDIR build
COPY . .
RUN mvn clean package -pl :at-application-bootstrap -am

FROM eclipse-temurin:21-jre
COPY --from=build /build/at-application-bootstrap/target/at-application-bootstrap-exec.jar application.jar
ENV JAVA_OPTIONS \
    -Dfile.encoding=UTF-8
EXPOSE 8080
SHELL ["/bin/bash", "-c"]
CMD bash -c "java ${JAVA_OPTIONS} -jar application.jar"